name: Release Workflow

on:
  push:
    branches:
      - release  # Trigger on pushes to the 'release' branch

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Build for WASM
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Bindgen & Package Npm 
        run: |
          cargo install wasm-pack
          wasm-pack build --target web --out-dir renderer
          tar -cvzf renderer.tar.gz renderer

      - name: Upload Compiled Artifact
        uses: actions/upload-artifact@v4
        with:
          name: renderer.tar.gz
          path: renderer.tar.gz

      - id: create-release-name
        name: Create Release Name
        run: |
          id=$(echo ${{ github.sha }} | cut -c1-7)
          echo "::set-output name=id::$id"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{steps.create-release-name.outputs.id}}
          name: Release ${{steps.create-release-name.outputs.id}}
          draft: false
          prerelease: false
          files: renderer.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
