name: Release Workflow

on:
  push:
    branches:
      - release  # Trigger on pushes to the 'release' branch

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.80.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run Tests
        run: cargo test

      - name: Build for WASM
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Execute Additional Commands
        run: |
          ./bindgen.sh
          tar -cvzf renderer.tar.gz target/npm/renderer

      - name: Upload Compiled Artifact
        uses: actions/upload-artifact@v3
        with:
          name: renderer.tar.gz
          path: renderer.tar.gz

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Automated release for commit ${{ github.sha }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: renderer.tar.gz
          asset_name: renderer.tar.gz
          asset_content_type: application/wasm
